Etimo/etimo-achievements

packages/api/src/resources/awards/awards-controller.ts
packages/api/src/resources/awards/index.ts
packages/api/src/resources/index.ts
packages/api/src/server.ts

The end-points include the documentation in terms
of Swagger but they are not yet implemented.

docs: add documented end-points.

---

packages/api/src/resources/achievements/achievement-controller.ts
packages/api/src/resources/users/user-controller.ts

Adding documentation to /achievements and /users endpoints.

docs: add swagger docs to existing endpoints

---

packages/api/src/resources/awards/awards-controller.ts
packages/api/src/resources/awards/awards-dto.ts
packages/api/src/resources/awards/awards-mapper.ts
packages/api/src/resources/awards/awards-validator.ts
packages/api/src/resources/awards/index.ts
packages/data/src/models/index.ts
packages/data/src/repositories/user-achievement-repository.ts
packages/service/src/modules/awards/get-awards-service.ts
packages/service/src/modules/awards/index.ts
packages/service/src/modules/common/service-options.ts
packages/service/src/modules/index.ts

Implmentation of /GET request for the awards api.
Should return all the awards with pagnation.

feat: add awards api /GET

---

packages/api/src/resources/awards/awards-controller.ts
packages/data/src/models/user-achievement-model.ts
packages/service/src/modules/awards/create-awards-service.ts
packages/service/src/modules/awards/index.ts

Add implementation for /awards POST api.
Should be able to create an award.

feat: add /awards POST api

---

packages/api/src/openapi.json
packages/api/src/resources/slack/index.ts
packages/api/src/resources/slack/slack-command-controller.ts
packages/api/src/server.ts
packages/service/src/modules/slack/create-achievements-service.ts
packages/service/src/modules/slack/index.ts
packages/service/src/modules/slack/modals/create-achievement-modal-open.ts
packages/service/src/modules/slack/modals/intex.ts
packages/service/src/modules/slack/show-achievements-service.ts
packages/service/src/modules/slack/utils.ts

New API for slack to interact with to create an achievement.

feat: add command api for create achievement

---

packages/api/src/openapi.json
packages/api/src/resources/achievements/achievement-controller.ts
packages/api/src/resources/awards/award-controller.ts
packages/api/src/resources/slack/slack-command-controller.ts
packages/api/src/resources/users/user-controller.ts
packages/api/src/resources/version/version-controller.ts

docs: improve api documentation

---

.docker/Dockerfiles/nodemon
.docker/entrypoints/nodemon.sh
.dockerignore
docker-compose.yml
packages/api/openapi/definition.ts
packages/api/openapi/objects/id-object.yml
packages/api/openapi/parameters/award-id-param.yml
packages/api/openapi/properties/id-property.yml
packages/api/src/middleware/api-key-middleware.ts
packages/api/src/middleware/error-middleware.ts
packages/api/src/middleware/logging-middleware.ts
packages/api/src/openapi.json
packages/api/src/resources/achievements/achievement-controller.ts
packages/api/src/resources/achievements/achievement-dto.ts
packages/api/src/resources/awards/award-controller.ts
packages/api/src/resources/awards/award-dto.ts
packages/api/src/resources/slack/slack-command-controller.ts
packages/api/src/resources/slack/slack-controller.ts
packages/api/src/resources/users/user-controller.ts
packages/api/src/resources/users/user-dto.ts
packages/api/src/resources/version/version-controller.ts
packages/api/src/server.ts
packages/api/src/utils/endpoint-helper.ts
packages/common/src/logger.ts
packages/data/src/repositories/user-achievement-repository.ts
scripts/build-updated-packages.sh

docs: swagger/openapi improvements
scripts: improved nodemon support
fix: improved models & updated column names

fix: cleanup & improvements

---

.husky/pre-commit
package.json
tsconfig.json

chore: add pre-commit hooks

---

.vscode/extensions.json
.vscode/settings.json
package.json
scripts/install-vscode-extensions.js
scripts/utils/get-build-date.js
scripts/utils/get-build-order.js
scripts/utils/get-version-info.js
scripts/utils/install-dependencies.js
scripts/utils/run-command.js
scripts/utils/run-script.js
scripts/utils/set-build-date.js
scripts/utils/update-references.js
scripts/utils/verify-release.js
scripts/utils/which.js

chore: improve vscode configuration

---

package.json
packages/api/package.json
packages/common/package.json
packages/data/package.json
packages/express-middleware/package.json
packages/security/package.json
packages/service/package.json
packages/types/package.json
scripts/copy-env.js
scripts/remove-path.js
scripts/utils/file-helper.js
scripts/utils/run-command.js

Should make it possible to bootstrap the project on windows OS.

fix: fix bootstrap for windows

---

packages/api/src/openapi.json
packages/api/src/resources/users/user-dto.ts
packages/api/src/resources/users/user-mapper.ts
packages/data/migrations/20220224000001_simplify_user_table.ts
packages/data/seeds/00-users.ts
packages/data/src/models/user-model.ts
packages/service/src/modules/user/user.spec.ts
packages/types/src/user.ts

We don't need a username or password so they are removed and replaced by a name for the user.

refactor: change user table

---

packages/api/src/middleware/error-middleware.ts

fix: don't expose errors

---

packages/web/src/common/hooks/use-has-access.ts
packages/web/src/components/RequirePermission.tsx
packages/web/src/components/SideMenu.tsx
packages/web/src/components/table/PaginatedTable.tsx
packages/web/src/features/achievements/AchievementCreate.tsx
packages/web/src/features/achievements/AchievementList.tsx
packages/web/src/features/awards/AwardList.tsx
packages/web/src/features/users/UserList.tsx
packages/web/src/features/users/UserProfile.tsx

feat: hide features the user does not have access to

---

packages/api/src/middleware/error-middleware.ts
packages/api/src/utils/endpoint-helper.ts
packages/common/src/errors/forbidden-error.ts
packages/common/src/errors/index.ts

fix: return 403 on insufficient scope

---

packages/data/migrations/20220423165830_cascade_delete_on_access_token.ts

fix: cascade delete on access tokens

---

packages/web/src/app/App.tsx
packages/web/src/app/styles/index.css

fix: menu height

---

.docker/resources/nginx.conf

fix: add security headers to nginx

---

.docker/dockerfiles/api
.docker/dockerfiles/web
.docker/resources/version.json.template
.github/actions/docker-build-push/action.yml
packages/api/src/resources/version/version.json
scripts/build-docker.js

feat: add build number to version information

---

packages/service/src/modules/auth/login-service.ts
packages/web/src/common/hooks/use-has-scope.ts
packages/web/src/components/RequirePermission.tsx
packages/web/src/components/SideMenu.tsx
packages/web/src/version.json

feat: show version in web menu

---

packages/web/src/common/hooks/use-remove-query-param.ts
packages/web/src/components/ConfirmModal.tsx
packages/web/src/components/Modal.tsx
packages/web/src/components/SideMenu.tsx
packages/web/src/components/buttons/TrashButton.tsx
packages/web/src/components/cards/Card.tsx
packages/web/src/features/achievements/AchievementList.tsx
packages/web/src/features/awards/AwardList.tsx
packages/web/src/features/users/UserList.tsx
packages/web/src/features/users/UserProfile.tsx

feat: confirm deletion

---

packages/api/openapi/parameters/page-token-param.yml
packages/api/src/openapi.json
packages/api/src/resources/awards/award-controller.ts
packages/api/src/resources/highscore/highscore-controller.ts
packages/api/src/resources/users/user-controller.ts
packages/api/src/utils/pagination-helper.ts
packages/common/src/paginate.ts
packages/web/src/common/hooks/use-replace-query-param.ts
packages/web/src/common/utils/query-helper.ts
packages/web/src/components/table/PaginatedTable.tsx
packages/web/src/components/table/TableHeader.tsx
packages/web/src/features/achievements/AchievementList.tsx
packages/web/src/features/achievements/achievement-api.ts
packages/web/src/features/achievements/achievement-service.ts
packages/web/src/features/awards/AwardList.tsx
packages/web/src/features/awards/award-api.ts
packages/web/src/features/awards/award-service.ts
packages/web/src/features/highscore/Highscore.tsx
packages/web/src/features/highscore/highscore-api.ts
packages/web/src/features/highscore/highscore-service.ts
packages/web/src/features/users/UserList.tsx
packages/web/src/features/users/user-api.ts
packages/web/src/features/users/user-service.ts

feat: sort order in tables

---

packages/common/src/logger.ts
packages/types/src/interfaces/logger.ts

feat: improved logging with context

---

packages/api/src/context.ts
packages/api/src/middleware/context-middleware.ts
packages/types/src/interfaces/logger.ts
packages/utils/src/logger/context-logger.ts
packages/utils/src/logger/dev-logger.ts
packages/utils/src/logger/winston-logger.ts

feat: add more content to logging context

---

packages/api/src/index.ts
packages/api/src/resources/auth/auth-controller.ts
packages/api/src/server.ts
packages/api/src/test/request-helper.ts
packages/api/src/utils/endpoint-helper.ts
packages/api/src/utils/setup-helper.ts
packages/common/src/api/api.ts
packages/common/src/env-helper.ts
packages/security/package.json
packages/security/src/encryption-helper.ts
packages/security/src/oauth/jwt-service.ts
packages/security/src/oauth/providers/google-oauth-service.ts
packages/security/tsconfig.json
packages/service/src/modules/slack/award-achievement-interact-service.ts
packages/service/src/modules/slack/award-achievement-service.ts
packages/service/src/modules/slack/sync-users-service.ts
packages/service/src/modules/slack/utils.ts
packages/utils/package.json
packages/utils/src/chat/slack-notify-service.ts
packages/utils/src/env.ts
packages/utils/src/feature/unleash-feature-service.ts
packages/utils/src/index.ts
packages/utils/tsconfig.json
yarn.lock

fix: move get env variable to utils

---

packages/common/src/api/achievement-api.ts
packages/common/src/api/api.ts
packages/common/src/api/authorized-api.ts
packages/common/src/api/award-api.ts
packages/common/src/api/feature-api.ts
packages/common/src/api/highscore-api.ts
packages/common/src/api/user-api.ts
packages/web/src/features/achievements/achievement-utils.ts
packages/web/src/features/auth/Authentication.tsx
packages/web/src/features/awards/award-utils.ts
packages/web/src/features/feature/hooks/use-feature-enabled.ts
packages/web/src/features/highscore/highscore-utils.ts
packages/web/src/features/users/user-utils.ts

feat: refresh token on failed get requests

---

.vscode/launch.json
packages/web/webpack.common.js
packages/web/webpack.dev.js

chore: get web debug working

---

packages/web/src/features/awards/AwardList.tsx

feat: display description in awards list

---

packages/web/src/app/App.tsx
packages/web/src/components/form/FormSelect.tsx
packages/web/src/features/awards/AwardGive.tsx

Förra selecten hade lite buggar som jag inte testade :)
Closes: #255

feat: better select

---

packages/web/src/features/highscore/Highscore.tsx

Går även att sortera på rank
Closes: #297

feat: display rank in highscore

---

packages/api/src/openapi.json
packages/api/src/resources/highscore/highscore-mapper.ts
packages/common/src/dtos/highscore-dto.ts
packages/service/src/modules/highscore/get-highscore-service.ts
packages/types/src/highscore.ts
packages/web/src/features/highscore/Highscore.tsx
packages/web/src/features/highscore/highscore-types.ts
packages/web/src/features/highscore/highscore-utils.ts

- Added a 10% kickback on achievements, with a maximum score of 50 points. Kickback is not granted on self-awards.
- Added a total score, which is achievements points + kickback points
- Display these scores in highscore table
Closes: #317

feat: kickback score and total score

---

packages/api/src/openapi.json
packages/api/src/resources/highscore/highscore-mapper.ts
packages/common/src/dtos/highscore-dto.ts
packages/service/src/modules/highscore/get-highscore-service.ts
packages/types/src/highscore.ts
packages/web/src/features/highscore/Highscore.tsx
packages/web/src/features/highscore/highscore-types.ts
packages/web/src/features/highscore/highscore-utils.ts

Adds a new highscore entry: points per achievement
Closes: #346

feat: points per achievement

---

packages/web/src/features/awards/AwardGive.tsx
packages/web/src/features/awards/award-utils.ts

feat: sort awards by most used

---

packages/api/src/openapi.json
packages/api/src/resources/slack/slack-controller.ts
packages/api/src/resources/users/user-controller.ts
packages/common/src/api/index.ts
packages/common/src/api/slack-api.ts
packages/common/src/dtos/user-dto.ts
packages/service/src/modules/award/give-award-service.ts
packages/service/src/modules/slack/sync-users-service.ts
packages/web/src/app/Router.tsx
packages/web/src/components/SideMenu.tsx
packages/web/src/features/users/UserCreate.tsx
packages/web/src/features/users/UserEditModal.tsx
packages/web/src/features/users/UserProfileEditModal.tsx
packages/web/src/features/users/UserSlackSync.tsx

- Add manual sync of slack handles
- Add automatic sync of slack handle upon user creation and user update
- Remove ability to manually set slack handles
Closes: #318

feat: tag users in slack and slack handle sync

---

.docker/resources/nginx.conf
.github/workflows/cd-prod.yml
.github/workflows/cd-staging.yml
packages/web/src/components/Avatar.tsx

Verifierade cors-fixen genom att editera dom:en i devtools på prod-sidan

fix: fix env variables and fix image cors issue

---

packages/web/src/app/App.tsx
packages/web/src/app/styles/theme.ts
packages/web/src/components/form/FormSelect.tsx
packages/web/src/features/awards/AwardGive.tsx

- Adds support to group options in dropdown
- Group achievements in give award view

feat: group options in dropdown

---

packages/service/package.json
packages/service/src/modules/award/give-award-service.ts
packages/service/src/modules/highscore/get-highscore-service.ts
packages/service/src/modules/highscore/get-higscore-service.test.ts

self award
kickback (slack-handeln är fel)
Closes: #353

feat: print kickback in slack

---

packages/web/src/components/buttons/FavoriteButton.tsx
packages/web/src/components/table/PaginatedTable.tsx
packages/web/src/features/achievements/AchievementList.tsx
packages/web/src/features/awards/AwardGive.tsx
packages/web/src/hooks/use-favorite-achievement.ts

feat: ability to favorite achievements in achievements list

---

packages/service/src/modules/award/give-award-service.ts
packages/types/src/interfaces/notify-service.ts
packages/utils/src/chat/slack-notify-service.ts

feat: print achievement description in slack

---

packages/api/src/context.ts
packages/api/src/openapi.json
packages/api/src/resources/achievements/achievement-controller.ts
packages/api/src/resources/achievements/achievement-mapper.ts
packages/common/src/dtos/achievement-dto.ts
packages/data/migrations/20221110085330_add-self-awardable-field.ts
packages/data/seeds/01-achievements.ts
packages/data/src/models/achievement-model.ts
packages/service/src/modules/award/give-award-service.ts
packages/types/src/achievement.ts
packages/web/src/components/form/FormCheckbox.tsx
packages/web/src/components/form/index.ts
packages/web/src/features/achievements/AchievementCreate.tsx
packages/web/src/features/achievements/AchievementEditModal.tsx
packages/web/src/features/achievements/AchievementList.tsx
packages/web/src/features/awards/AwardGive.tsx

feat: self awardable achievements property

---

packages/api/openapi/objects/id-list-object.yml
packages/api/src/openapi.json
packages/api/src/resources/awards/award-controller.ts
packages/api/src/resources/awards/award-mapper.ts
packages/api/src/resources/awards/openapi/award-content.yml
packages/common/src/api/award-api.ts
packages/common/src/dtos/award-dto.ts
packages/service/src/modules/award/give-award-service.ts
packages/service/src/modules/slack/award-achievement-interact-service.ts
packages/types/src/award.ts
packages/web/src/features/awards/AwardGive.tsx
packages/web/src/features/awards/award-utils.ts

feat: give awards to multiple people

---

packages/api/src/openapi.json
packages/api/src/resources/achievements/achievement-mapper.ts
packages/common/src/dtos/achievement-dto.ts
packages/data/migrations/20221110140406_global_cooldowns.ts
packages/data/seeds/01-achievements.ts
packages/data/src/models/achievement-model.ts
packages/data/src/repositories/award-repository.ts
packages/service/src/modules/award/give-award-service.ts
packages/types/src/achievement.ts
packages/web/src/components/cards/CardRow.tsx
packages/web/src/components/form/FormCheckbox.tsx
packages/web/src/components/form/FormTextInput.tsx
packages/web/src/features/achievements/AchievementCreate.tsx
packages/web/src/features/achievements/AchievementEditModal.tsx
packages/web/src/features/achievements/AchievementList.tsx

feat: add support for global cooldowns

---

.github/actions/deploy-kubernetes/action.yml
.github/actions/docker-build-push/action.yml
.github/scripts/tag-release.sh
.github/workflows/cd-prod.yml
.github/workflows/cd-staging.yml

Due to set-output being deprecated.

chore: update github action
